import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { BackgroundGradientAnimation } from "@/components/ui/BackgroundGradientAnimation";

const inter = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${inter.className} bg-backgroundDark-1000`}>{children}</body>
    </html>
  );
}
